#!/bin/sh

S3_BUCKET=${S3_BUCKET#"s3://"}
S3_BUCKET=${S3_BUCKET%"/"}

pg_dump --no-owner | gzip | s3cmd --access_key=${S3_ACCESS_KEY} --secret_key=${S3_SECRET_KEY} --host-bucket "%(bucket)s.${S3_ENDPOINT}" put - s3://${S3_BUCKET}/dumps/${PGDATABASE}_`date +"%Y%m%d%H%M%S"`.gz
s3cmd --access_key=${S3_ACCESS_KEY} --secret_key=${S3_SECRET_KEY} --host-bucket "%(bucket)s.${S3_ENDPOINT}" sync ${ZAMMAD_STORAGE_DIR%/} s3://${S3_BUCKET}/
